[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 1, y = 2 }
dynamic_padding = true
opacity = 1.0
blur = true

[font]
normal = { family = "Hurmit Nerd Font", style = "Regular" }
bold = { family = "Hurmit Nerd Font", style = "Bold" }
italic = { family = "Hurmit Nerd Font", style = "Italic" }
bold_italic = { family = "Hurmit Nerd Font", style = "Bold Italic" }
size = 11
builtin_box_drawing = true

[colors]
primary = { foreground = "#839496", background = "#001b26" }
